"""
FastAPI server for Robot web interface.

Provides a REST API for managing conversations with coding agents,
cookie-based authentication via one-time codes, folder browsing,
and real-time chat functionality. Uses SQLite with Peewee for persistence.

Authentication flow:
1. CLI generates a one-time auth code via `robot auth`
2. User visits the link (or scans QR code)
3. Server validates code and sets a long-term browser cookie
4. Cookie is used to create/renew 1-week sessions
"""

import asyncio
import hashlib
import json
import logging
import os
import secrets
import subprocess
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Depends, Request, Response, Cookie
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, FileResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from peewee import (
    Model, SqliteDatabase, CharField, TextField, DateTimeField,
    ForeignKeyField, BooleanField, IntegerField
)
from pydantic import BaseModel
from sse_starlette.sse import EventSourceResponse

from robot import Robot
from robot.base import AgentConfig
from robot.status import StatusCallback, StatusEvent as StatusEventModel, StatusType
from robot.routes import browser_router

logger = logging.getLogger(__name__)

# Database setup
DB_PATH = Path("/tmp/robot/robot_web.db")
DB_PATH.parent.mkdir(parents=True, exist_ok=True)
db = SqliteDatabase(str(DB_PATH))

# Auth configuration
AUTH_CODE_EXPIRY_HOURS = 1  # One-time codes expire after 1 hour
SESSION_EXPIRY_DAYS = 7  # Sessions last 1 week
SESSION_RENEWAL_HOURS = 1  # Renew session on first request per hour
COOKIE_NAME = "robot_session"
COOKIE_MAX_AGE = 60 * 60 * 24 * 365  # 1 year for long-term cookie

# Default working directory for projects
DEFAULT_CODE_DIR = Path.home() / "Code"


# Database models
class BaseDBModel(Model):
    class Meta:
        database = db


class AuthCode(BaseDBModel):
    """One-time authentication code generated by CLI."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    code = CharField(unique=True, max_length=64)
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    expires_at = DateTimeField()
    used = BooleanField(default=False)


class Session(BaseDBModel):
    """Browser session for authenticated access."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    token = CharField(unique=True, max_length=64)  # Long-term browser token
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    expires_at = DateTimeField()
    last_active = DateTimeField(default=lambda: datetime.now(timezone.utc))
    is_active = BooleanField(default=True)


class Conversation(BaseDBModel):
    """Chat conversation with an agent."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    session = ForeignKeyField(Session, backref='conversations', null=True)
    title = CharField(max_length=256, default="New Conversation")
    working_dir = CharField(max_length=512)
    agent = CharField(max_length=32, default="claude")
    model = CharField(max_length=64, default="opus")
    claude_session_id = CharField(max_length=128, null=True)  # Claude session for resume
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    updated_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    is_active = BooleanField(default=True)


class Message(BaseDBModel):
    """Individual message in a conversation."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    conversation = ForeignKeyField(Conversation, backref='messages')
    role = CharField(max_length=16)  # user, assistant, system
    content = TextField()
    raw_response = TextField(null=True)  # Raw JSON from agent
    files_modified = TextField(null=True)  # JSON list of modified files
    actions = TextField(null=True)  # JSON list of actions taken
    duration = IntegerField(null=True)  # Response time in ms
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))


class ModifiedFile(BaseDBModel):
    """Track files modified during a conversation."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    conversation = ForeignKeyField(Conversation, backref='modified_files')
    file_path = CharField(max_length=512)
    original_hash = CharField(max_length=64, null=True)
    modified_hash = CharField(max_length=64, null=True)
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))


class StatusEvent(BaseDBModel):
    """Status event during message processing."""
    id = CharField(primary_key=True, default=lambda: str(uuid.uuid4()))
    message = ForeignKeyField(Message, backref='status_events', null=True)
    conversation = ForeignKeyField(Conversation, backref='status_events')
    event_type = CharField(max_length=32)  # init, tool_start, tool_complete, etc.
    status_message = TextField()
    tool_name = CharField(max_length=64, null=True)
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))


# Create tables
db.connect()
db.create_tables([AuthCode, Session, Conversation, Message, ModifiedFile, StatusEvent])


# Pydantic models for API
class ConversationCreate(BaseModel):
    title: Optional[str] = None
    working_dir: str
    agent: str = "claude"
    model: str = "opus"


class ConversationUpdate(BaseModel):
    title: Optional[str] = None
    is_active: Optional[bool] = None


class MessageCreate(BaseModel):
    content: str


class FolderCreate(BaseModel):
    name: str
    parent_path: str


class ConversationResponse(BaseModel):
    id: str
    title: str
    working_dir: str
    agent: str
    model: str
    created_at: datetime
    updated_at: datetime
    message_count: int = 0


class ActionItem(BaseModel):
    """An action taken by the agent (command, file operation, etc.)."""
    type: str  # command, read, write, edit, delete, search, tool
    name: str  # Short display name
    detail: str  # Full path or command
    icon: str  # Emoji icon
    color: str  # CSS color class


class MessageResponse(BaseModel):
    id: str
    role: str
    content: str
    files_modified: Optional[list] = None
    actions: Optional[list[ActionItem]] = None
    duration: Optional[int] = None
    created_at: datetime


class ModifiedFileResponse(BaseModel):
    id: str
    file_path: str
    can_diff: bool = True


class FolderItem(BaseModel):
    name: str
    path: str
    is_dir: bool


class StatusEventResponse(BaseModel):
    id: str
    event_type: str
    message: str
    tool_name: Optional[str] = None
    created_at: datetime


# Action type mappings for UI display
ACTION_CONFIGS = {
    "Bash": {"icon": "⚡", "color": "action-command", "type": "command"},
    "Read": {"icon": "📖", "color": "action-read", "type": "read"},
    "Write": {"icon": "✏️", "color": "action-write", "type": "write"},
    "Edit": {"icon": "🔧", "color": "action-edit", "type": "edit"},
    "Glob": {"icon": "🔍", "color": "action-search", "type": "search"},
    "Grep": {"icon": "🔎", "color": "action-search", "type": "search"},
    "Task": {"icon": "🤖", "color": "action-agent", "type": "agent"},
    "TodoWrite": {"icon": "📋", "color": "action-tool", "type": "tool"},
    "WebFetch": {"icon": "🌐", "color": "action-web", "type": "web"},
    "WebSearch": {"icon": "🔍", "color": "action-web", "type": "web"},
}


def status_event_to_action(event: StatusEventModel) -> Optional[ActionItem]:
    """Convert a status event to an ActionItem for display."""
    if event.type != StatusType.TOOL_START or not event.tool_name:
        return None

    tool_name = event.tool_name
    config = ACTION_CONFIGS.get(tool_name, {"icon": "🔧", "color": "action-tool", "type": "tool"})

    # Extract meaningful detail from tool input
    detail = ""
    name = tool_name

    if event.tool_input:
        if tool_name == "Bash":
            cmd = event.tool_input.get("command", "")
            desc = event.tool_input.get("description", "")
            name = desc if desc else (cmd[:40] + "..." if len(cmd) > 40 else cmd)
            detail = cmd
        elif tool_name in ("Read", "Write", "Edit"):
            path = event.tool_input.get("file_path", "")
            name = path.split("/")[-1] if path else tool_name
            detail = path
        elif tool_name == "Glob":
            pattern = event.tool_input.get("pattern", "")
            name = f"glob: {pattern}"
            detail = pattern
        elif tool_name == "Grep":
            pattern = event.tool_input.get("pattern", "")
            name = f"grep: {pattern[:30]}" if len(pattern) > 30 else f"grep: {pattern}"
            detail = pattern
        elif tool_name == "Task":
            desc = event.tool_input.get("description", "")
            name = desc if desc else "Subagent"
            detail = event.tool_input.get("prompt", "")[:100]
        else:
            name = event.message[:40] if event.message else tool_name
            detail = str(event.tool_input)[:200]

    return ActionItem(
        type=config["type"],
        name=name,
        detail=detail,
        icon=config["icon"],
        color=config["color"]
    )


# Web-specific prompt prefix for UI feedback
WEB_PROMPT_PREFIX = """
You are running in a web interface. Provide clear, concise status updates as you work.
Format your responses for readability in a chat UI. Use markdown formatting.

When working on tasks:
1. Briefly acknowledge what you're doing
2. Show key findings or changes
3. Summarize results clearly

Keep explanations focused and avoid unnecessary verbosity.
If you modify files, mention which files were changed.
"""


# FastAPI app
app = FastAPI(
    title="Robot Web API",
    description="API for Robot coding agent web interface",
    version="0.1.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(browser_router)


# Datetime utilities
def parse_db_datetime(dt) -> datetime:
    """Parse datetime from database (may be string or datetime)."""
    if isinstance(dt, datetime):
        return dt
    if isinstance(dt, str):
        # Handle ISO format with or without timezone
        dt = dt.replace('Z', '+00:00')
        try:
            return datetime.fromisoformat(dt)
        except ValueError:
            # Fallback for different formats
            return datetime.strptime(dt, "%Y-%m-%d %H:%M:%S.%f")
    return dt


# Auth utilities
def create_auth_code() -> AuthCode:
    """Create a new one-time authentication code."""
    code = secrets.token_urlsafe(32)
    expires_at = datetime.now(timezone.utc) + timedelta(hours=AUTH_CODE_EXPIRY_HOURS)
    return AuthCode.create(code=code, expires_at=expires_at)


def verify_session(request: Request) -> Session:
    """Verify session from cookie and return session object."""
    token = request.cookies.get(COOKIE_NAME)
    if not token:
        raise HTTPException(status_code=401, detail="Not authenticated")

    session = Session.get_or_none(
        (Session.token == token) &
        (Session.is_active == True)
    )

    if not session:
        raise HTTPException(status_code=401, detail="Invalid session")

    now = datetime.now(timezone.utc)
    expires_at = parse_db_datetime(session.expires_at)
    last_active = parse_db_datetime(session.last_active)

    # Check if session expired
    if expires_at < now:
        session.is_active = False
        session.save()
        raise HTTPException(status_code=401, detail="Session expired")

    # Renew session if first request in the last hour
    if last_active < now - timedelta(hours=SESSION_RENEWAL_HOURS):
        session.expires_at = now + timedelta(days=SESSION_EXPIRY_DAYS)
        session.last_active = now
        session.save()
    elif last_active < now - timedelta(minutes=1):
        # Update last_active less frequently to reduce DB writes
        session.last_active = now
        session.save()

    return session


def get_session(request: Request) -> Session:
    """Dependency to get current session."""
    return verify_session(request)


# Auth endpoints
@app.get("/api/auth/verify")
async def verify_auth_code(code: str, response: Response):
    """
    Verify a one-time auth code and create a session.

    Returns a redirect to the main page with session cookie set.
    """
    auth_code = AuthCode.get_or_none(
        (AuthCode.code == code) &
        (AuthCode.used == False)
    )

    if not auth_code:
        raise HTTPException(status_code=401, detail="Invalid or expired code")

    now = datetime.now(timezone.utc)
    expires_at = parse_db_datetime(auth_code.expires_at)

    if expires_at < now:
        raise HTTPException(status_code=401, detail="Code expired")

    # Mark code as used
    auth_code.used = True
    auth_code.save()

    # Create new session
    session_token = secrets.token_urlsafe(48)
    session = Session.create(
        token=session_token,
        expires_at=now + timedelta(days=SESSION_EXPIRY_DAYS)
    )

    # Set cookie and redirect to main page
    redirect = RedirectResponse(url="/", status_code=302)
    redirect.set_cookie(
        key=COOKIE_NAME,
        value=session_token,
        max_age=COOKIE_MAX_AGE,
        httponly=True,
        samesite="lax"
    )
    return redirect


@app.get("/api/auth/status")
async def auth_status(request: Request):
    """Check if the current session is valid."""
    try:
        session = verify_session(request)
        return {"authenticated": True, "session_id": session.id}
    except HTTPException:
        return {"authenticated": False}


@app.post("/api/auth/logout")
async def logout(request: Request, response: Response):
    """Logout and invalidate session."""
    token = request.cookies.get(COOKIE_NAME)
    if token:
        session = Session.get_or_none(Session.token == token)
        if session:
            session.is_active = False
            session.save()

    response.delete_cookie(COOKIE_NAME)
    return {"status": "logged out"}


# Folder endpoints
@app.get("/api/folders", response_model=list[FolderItem])
async def list_folders(
    path: Optional[str] = None,
    session: Session = Depends(get_session)
):
    """List folders in a directory."""
    base_path = Path(path) if path else DEFAULT_CODE_DIR

    if not base_path.exists():
        raise HTTPException(status_code=404, detail="Directory not found")

    if not base_path.is_dir():
        raise HTTPException(status_code=400, detail="Path is not a directory")

    items = []
    try:
        for item in sorted(base_path.iterdir()):
            # Skip hidden files and common non-project dirs
            if item.name.startswith('.'):
                continue
            if item.name in ['node_modules', '__pycache__', 'venv', '.venv']:
                continue

            items.append(FolderItem(
                name=item.name,
                path=str(item),
                is_dir=item.is_dir()
            ))
    except PermissionError:
        raise HTTPException(status_code=403, detail="Permission denied")

    return items


@app.post("/api/folders", response_model=FolderItem)
async def create_folder(
    folder: FolderCreate,
    session: Session = Depends(get_session)
):
    """Create a new folder."""
    parent = Path(folder.parent_path)
    if not parent.exists():
        raise HTTPException(status_code=404, detail="Parent directory not found")

    new_folder = parent / folder.name
    if new_folder.exists():
        raise HTTPException(status_code=400, detail="Folder already exists")

    try:
        new_folder.mkdir(parents=True)
        return FolderItem(
            name=folder.name,
            path=str(new_folder),
            is_dir=True
        )
    except PermissionError:
        raise HTTPException(status_code=403, detail="Permission denied")


# Conversation endpoints
@app.get("/api/conversations", response_model=list[ConversationResponse])
async def list_conversations(session: Session = Depends(get_session)):
    """List all conversations for the current session."""
    conversations = (
        Conversation
        .select()
        .where(
            (Conversation.session == session) &
            (Conversation.is_active == True)
        )
        .order_by(Conversation.updated_at.desc())
    )

    result = []
    for conv in conversations:
        msg_count = Message.select().where(Message.conversation == conv).count()
        result.append(ConversationResponse(
            id=conv.id,
            title=conv.title,
            working_dir=conv.working_dir,
            agent=conv.agent,
            model=conv.model,
            created_at=conv.created_at,
            updated_at=conv.updated_at,
            message_count=msg_count
        ))
    return result


@app.post("/api/conversations", response_model=ConversationResponse)
async def create_conversation(
    conv_data: ConversationCreate,
    session: Session = Depends(get_session)
):
    """Create a new conversation."""
    working_dir = Path(conv_data.working_dir)
    if not working_dir.exists():
        raise HTTPException(status_code=404, detail="Working directory not found")

    title = conv_data.title or working_dir.name
    conv = Conversation.create(
        session=session,
        title=title,
        working_dir=str(working_dir),
        agent=conv_data.agent,
        model=conv_data.model
    )

    return ConversationResponse(
        id=conv.id,
        title=conv.title,
        working_dir=conv.working_dir,
        agent=conv.agent,
        model=conv.model,
        created_at=conv.created_at,
        updated_at=conv.updated_at,
        message_count=0
    )


@app.get("/api/conversations/{conv_id}", response_model=ConversationResponse)
async def get_conversation(conv_id: str, session: Session = Depends(get_session)):
    """Get a specific conversation."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    msg_count = Message.select().where(Message.conversation == conv).count()
    return ConversationResponse(
        id=conv.id,
        title=conv.title,
        working_dir=conv.working_dir,
        agent=conv.agent,
        model=conv.model,
        created_at=conv.created_at,
        updated_at=conv.updated_at,
        message_count=msg_count
    )


@app.patch("/api/conversations/{conv_id}", response_model=ConversationResponse)
async def update_conversation(
    conv_id: str,
    updates: ConversationUpdate,
    session: Session = Depends(get_session)
):
    """Update a conversation."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    if updates.title is not None:
        conv.title = updates.title
    if updates.is_active is not None:
        conv.is_active = updates.is_active

    conv.updated_at = datetime.now(timezone.utc)
    conv.save()

    msg_count = Message.select().where(Message.conversation == conv).count()
    return ConversationResponse(
        id=conv.id,
        title=conv.title,
        working_dir=conv.working_dir,
        agent=conv.agent,
        model=conv.model,
        created_at=conv.created_at,
        updated_at=conv.updated_at,
        message_count=msg_count
    )


@app.delete("/api/conversations/{conv_id}")
async def delete_conversation(conv_id: str, session: Session = Depends(get_session)):
    """Delete (deactivate) a conversation."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    conv.is_active = False
    conv.save()
    return {"status": "deleted"}


# Message endpoints
@app.get("/api/conversations/{conv_id}/messages", response_model=list[MessageResponse])
async def list_messages(conv_id: str, session: Session = Depends(get_session)):
    """List all messages in a conversation."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    messages = (
        Message
        .select()
        .where(Message.conversation == conv)
        .order_by(Message.created_at)
    )

    result = []
    for msg in messages:
        files = json.loads(msg.files_modified) if msg.files_modified else None
        actions = None
        if msg.actions:
            actions_data = json.loads(msg.actions)
            actions = [ActionItem(**a) for a in actions_data]
        result.append(MessageResponse(
            id=msg.id,
            role=msg.role,
            content=msg.content,
            files_modified=files,
            actions=actions,
            duration=msg.duration,
            created_at=msg.created_at
        ))
    return result


def compute_file_hash(file_path: Path) -> Optional[str]:
    """Compute SHA256 hash of a file."""
    if not file_path.exists():
        return None
    try:
        return hashlib.sha256(file_path.read_bytes()).hexdigest()[:16]
    except Exception:
        return None


def track_modified_files(conv: Conversation, working_dir: Path) -> list[str]:
    """Track which files have been modified since last check."""
    modified = []

    # Get all tracked files for this conversation
    tracked = {f.file_path: f for f in conv.modified_files}

    # Check git status for modifications
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            cwd=working_dir,
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            for line in result.stdout.strip().split('\n'):
                if line:
                    file_path = str(working_dir / line)
                    if file_path not in tracked:
                        ModifiedFile.create(
                            conversation=conv,
                            file_path=file_path,
                            original_hash=compute_file_hash(Path(file_path))
                        )
                    modified.append(file_path)
    except Exception as e:
        logger.warning(f"Failed to track files: {e}")

    return modified


@app.post("/api/conversations/{conv_id}/messages", response_model=MessageResponse)
async def send_message(
    conv_id: str,
    message: MessageCreate,
    session: Session = Depends(get_session)
):
    """Send a message and get agent response."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    # Store user message
    user_msg = Message.create(
        conversation=conv,
        role="user",
        content=message.content
    )

    # Configure agent
    config = AgentConfig(
        model=conv.model,
        working_dir=Path(conv.working_dir),
        prompt_prefix=WEB_PROMPT_PREFIX,
        session_id=conv.claude_session_id,
        resume=conv.claude_session_id is not None
    )

    # Run agent
    start_time = time.time()
    try:
        agent = Robot.get(conv.agent, config=config)
        response = agent.run(
            prompt=message.content,
            working_dir=Path(conv.working_dir)
        )

        duration_ms = int((time.time() - start_time) * 1000)

        # Track modified files
        files_modified = track_modified_files(conv, Path(conv.working_dir))

        # Update session ID for resume capability
        if hasattr(response, 'session_id') and response.session_id:
            conv.claude_session_id = response.session_id
            conv.save()

        # Store assistant message
        assistant_msg = Message.create(
            conversation=conv,
            role="assistant",
            content=response.content if response.success else f"Error: {response.error}",
            raw_response=response.raw_output,
            files_modified=json.dumps(files_modified) if files_modified else None,
            duration=duration_ms
        )

        # Update conversation timestamp
        conv.updated_at = datetime.now(timezone.utc)
        conv.save()

        return MessageResponse(
            id=assistant_msg.id,
            role="assistant",
            content=assistant_msg.content,
            files_modified=files_modified,
            duration=duration_ms,
            created_at=assistant_msg.created_at
        )

    except Exception as e:
        logger.error(f"Agent error: {e}")

        error_msg = Message.create(
            conversation=conv,
            role="assistant",
            content=f"Error running agent: {str(e)}",
            duration=int((time.time() - start_time) * 1000)
        )

        return MessageResponse(
            id=error_msg.id,
            role="assistant",
            content=error_msg.content,
            files_modified=None,
            duration=error_msg.duration,
            created_at=error_msg.created_at
        )


@app.post("/api/conversations/{conv_id}/messages/stream")
async def send_message_stream(
    conv_id: str,
    message: MessageCreate,
    session: Session = Depends(get_session)
):
    """
    Send a message with streaming status updates via Server-Sent Events.

    Streams status events as the agent works, then sends the final response.
    Event types:
      - status: Real-time status update (tool start, tool complete, etc.)
      - message: Final assistant message
      - error: Error occurred
    """
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    async def event_generator():
        # Store user message
        user_msg = Message.create(
            conversation=conv,
            role="user",
            content=message.content
        )

        # Queue for status events from agent callback
        status_queue = asyncio.Queue()
        # Collect actions for persistent display
        collected_actions = []

        def on_status(event: StatusEventModel):
            """Callback to receive status events from the agent."""
            # Store status event in database
            StatusEvent.create(
                conversation=conv,
                event_type=event.type.value,
                status_message=event.message,
                tool_name=event.tool_name
            )
            # Convert to action if applicable
            action = status_event_to_action(event)
            if action:
                collected_actions.append(action)
            # Put event in queue for streaming
            try:
                status_queue.put_nowait(event)
            except asyncio.QueueFull:
                pass

        # Configure agent
        config = AgentConfig(
            model=conv.model,
            working_dir=Path(conv.working_dir),
            prompt_prefix=WEB_PROMPT_PREFIX,
            session_id=conv.claude_session_id,
            resume=conv.claude_session_id is not None
        )

        start_time = time.time()

        # Run agent in executor to not block event loop
        loop = asyncio.get_event_loop()

        def run_agent():
            agent = Robot.get(conv.agent, config=config)
            return agent.run(
                prompt=message.content,
                working_dir=Path(conv.working_dir),
                on_status=on_status
            )

        # Start agent task
        agent_task = loop.run_in_executor(None, run_agent)

        # Stream status events while agent runs
        try:
            while not agent_task.done():
                try:
                    # Wait for status events with timeout
                    event = await asyncio.wait_for(
                        status_queue.get(),
                        timeout=0.1
                    )
                    yield {
                        "event": "status",
                        "data": json.dumps({
                            "type": event.type.value,
                            "message": event.message,
                            "tool_name": event.tool_name
                        })
                    }
                except asyncio.TimeoutError:
                    continue

            # Drain remaining events
            while not status_queue.empty():
                event = status_queue.get_nowait()
                yield {
                    "event": "status",
                    "data": json.dumps({
                        "type": event.type.value,
                        "message": event.message,
                        "tool_name": event.tool_name
                    })
                }

            # Get agent response
            response = await agent_task
            duration_ms = int((time.time() - start_time) * 1000)

            # Track modified files
            files_modified = track_modified_files(conv, Path(conv.working_dir))

            # Serialize actions for storage
            actions_json = json.dumps([a.model_dump() for a in collected_actions]) if collected_actions else None

            # Store assistant message
            assistant_msg = Message.create(
                conversation=conv,
                role="assistant",
                content=response.content if response.success else f"Error: {response.error}",
                raw_response=response.raw_output,
                files_modified=json.dumps(files_modified) if files_modified else None,
                actions=actions_json,
                duration=duration_ms
            )

            # Update conversation timestamp
            conv.updated_at = datetime.now(timezone.utc)
            conv.save()

            # Send final message with actions
            yield {
                "event": "message",
                "data": json.dumps({
                    "id": assistant_msg.id,
                    "role": "assistant",
                    "content": assistant_msg.content,
                    "files_modified": files_modified,
                    "actions": [a.model_dump() for a in collected_actions],
                    "duration": duration_ms,
                    "created_at": assistant_msg.created_at.isoformat()
                })
            }

        except Exception as e:
            logger.error(f"Agent error: {e}")
            yield {
                "event": "error",
                "data": json.dumps({"error": str(e)})
            }

    return EventSourceResponse(event_generator())


# Modified files endpoints
@app.get("/api/conversations/{conv_id}/files", response_model=list[ModifiedFileResponse])
async def list_modified_files(conv_id: str, session: Session = Depends(get_session)):
    """List files modified in a conversation."""
    conv = Conversation.get_or_none(
        (Conversation.id == conv_id) &
        (Conversation.session == session)
    )
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    files = ModifiedFile.select().where(ModifiedFile.conversation == conv)
    return [
        ModifiedFileResponse(
            id=f.id,
            file_path=f.file_path,
            can_diff=Path(f.file_path).exists()
        )
        for f in files
    ]


@app.get("/api/files/diff")
async def get_file_diff(
    file_path: str,
    conv_id: Optional[str] = None,
    session: Session = Depends(get_session)
):
    """Get git diff for a file."""
    path = Path(file_path)
    if not path.exists():
        raise HTTPException(status_code=404, detail="File not found")

    try:
        result = subprocess.run(
            ["git", "diff", "HEAD", "--", str(path)],
            cwd=path.parent,
            capture_output=True,
            text=True,
            timeout=10
        )
        return {"diff": result.stdout, "file_path": file_path}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get diff: {e}")


@app.get("/api/files/content")
async def get_file_content(
    file_path: str,
    session: Session = Depends(get_session)
):
    """Get file content."""
    path = Path(file_path)
    if not path.exists():
        raise HTTPException(status_code=404, detail="File not found")

    try:
        content = path.read_text()
        return {"content": content, "file_path": file_path}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read file: {e}")


# Available models endpoint
@app.get("/api/models")
async def list_models(session: Session = Depends(get_session)):
    """List available models."""
    return {
        "claude": [
            {"id": "opus", "name": "Claude Opus 4", "default": True},
            {"id": "sonnet", "name": "Claude Sonnet 4"},
            {"id": "haiku", "name": "Claude Haiku 4"}
        ],
        "openrouter": [
            {"id": "opus", "name": "Claude Opus 4"},
            {"id": "sonnet", "name": "Claude Sonnet 4"},
            {"id": "deepseek", "name": "DeepSeek Chat"},
            {"id": "gpt5", "name": "GPT 5.2"},
            {"id": "gemini", "name": "Gemini 3 Pro"}
        ]
    }


# Static files directory
STATIC_DIR = Path(__file__).parent / "static"

# Mount static files
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


@app.get("/")
async def serve_index():
    """Serve the main frontend page."""
    return FileResponse(STATIC_DIR / "index.html")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
